django_app
Waiting for PostgreSQL...


db:5432 - accepting connections


PostgreSQL is ready!


Running migrations...


Traceback (most recent call last):


File "/app/manage.py", line 22, in <module>


main()


File "/app/manage.py", line 18, in main


execute_from_command_line(sys.argv)


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line


utility.execute()


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate


app_config = AppConfig.create(entry)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create


import_module(entry)


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked


ModuleNotFoundError: No module named 'apps.posts'


Collecting static files...


WARNING: migrate failed. Starting app without applying migrations.


Traceback (most recent call last):


File "/app/manage.py", line 22, in <module>


main()


File "/app/manage.py", line 18, in main


execute_from_command_line(sys.argv)


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line


utility.execute()


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate


app_config = AppConfig.create(entry)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create


import_module(entry)


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked


ModuleNotFoundError: No module named 'apps.posts'


Starting server...


[2025-10-27 08:27:16 +0000] [1] [INFO] Starting gunicorn 23.0.0

django_celery_beat
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1462, in __call__


return self.main(*args, **kwargs)


^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1383, in main


rv = self.invoke(ctx)


^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1850, in invoke


return _process_result(sub_ctx.command.invoke(sub_ctx))


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1246, in invoke


return ctx.invoke(self.callback, **ctx.params)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/click/core.py", line 814, in invoke


return callback(*args, **kwargs)


^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 34, in new_func


return f(get_current_context(), *args, **kwargs)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller


return f(ctx, *args, **kwargs)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/bin/beat.py", line 72, in beat


return beat().run()


^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/apps/beat.py", line 82, in run


self.init_loader()


File "/usr/local/lib/python3.12/site-packages/celery/apps/beat.py", line 132, in init_loader


self.app.loader.init_worker()


File "/usr/local/lib/python3.12/site-packages/celery/loaders/base.py", line 110, in init_worker


self.import_default_modules()


File "/usr/local/lib/python3.12/site-packages/celery/loaders/base.py", line 104, in import_default_modules


raise response


File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 280, in send


response = receiver(signal=self, sender=sender, **named)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 101, in on_import_modules


self.worker_fixup.validate_models()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 139, in validate_models


self.django_setup()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 135, in django_setup


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate


app_config = AppConfig.create(entry)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create


import_module(entry)


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked


ModuleNotFoundError: No module named 'apps.posts'


django_celery_worker

Waiting for PostgreSQL...


db:5432 - accepting connections


PostgreSQL is ready!


AUTO_MIGRATE is disabled; skipping migrations.


Collecting static files...


Traceback (most recent call last):


File "/app/manage.py", line 22, in <module>


main()


File "/app/manage.py", line 18, in main


execute_from_command_line(sys.argv)


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line


utility.execute()


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate


app_config = AppConfig.create(entry)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create


import_module(entry)


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked


ModuleNotFoundError: No module named 'apps.posts'


Starting server...


ERROR 2025-10-27 17:27:16,893 signal Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0xffffb8d61520>> raised: ModuleNotFoundError("No module named 'apps.posts'")


Traceback (most recent call last):


File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 280, in send


response = receiver(signal=self, sender=sender, **named)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 101, in on_import_modules


self.worker_fixup.validate_models()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 139, in validate_models


self.django_setup()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 135, in django_setup


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate


app_config = AppConfig.create(entry)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 193, in create


import_module(entry)


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked


ModuleNotFoundError: No module named 'apps.posts'